/---- CREACIÓN DE TABLAS PROYECTO 1 ----/

/---- OBJETO USUARIO ----/

CREATE TABLE Usuario (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre VARCHAR2(100),
usuario VARCHAR2(100),
password VARCHAR2(100)
);

/---- OBJETO DIRECCION ----/

CREATE TABLE Direccion (
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tipo VARCHAR2(100),
direccion VARCHAR2(100),
usuario int
);

/---- OBJETO PEDIDO ----/
CREATE TABLE Pedido(
id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
descripcion VARCHAR2(100),
valor int,
usuario int
);

ALTER TABLE direccion ADD CONSTRAINT usuario_direccion FOREIGN KEY(usuario) REFERENCES usuario (id);
ALTER TABLE pedido ADD CONSTRAINT usuario_pedido FOREIGN KEY(usuario) REFERENCES usuario (id);


-- Insertar datos en la tabla Usuario
INSERT INTO Usuario (nombre, usuario, password) VALUES ('Juan', 'juanito', '123456');
INSERT INTO Usuario (nombre, usuario, password) VALUES ('María', 'maria89', 'qwerty');
INSERT INTO Usuario (nombre, usuario, password) VALUES ('Pedro', 'pedrito', 'abc123');

-- Insertar datos en la tabla Dirección
INSERT INTO Direccion (tipo, direccion, usuario) VALUES ('Casa', 'Calle 123', 1);
INSERT INTO Direccion (tipo, direccion, usuario) VALUES ('Trabajo', 'Avenida Principal', 2);
INSERT INTO Direccion (tipo, direccion, usuario) VALUES ('Casa', 'Avenida Central', 3);

-- Insertar datos en la tabla Dirección
INSERT INTO Pedido (descripcion, valor, usuario) VALUES ('Pedido 1', 50000, 1);
INSERT INTO Pedido (descripcion, valor, usuario) VALUES ('Pedido 2', 100000, 2);
INSERT INTO Pedido (descripcion, valor, usuario) VALUES ('Pedido 3', 75000, 3);